CREATE OR REPLACE FUNCTION SP_CRM_PLATFORM_LIST_BUSINESSES()
RETURNS TABLE (
  BUSINESS_ID UUID,
  BUSINESS_NAME VARCHAR,
  BUSINESS_PHONE VARCHAR,
  BUSINESS_ACTIVE BOOLEAN,
  BUSINESS_CREATED_AT TIMESTAMP,

  USER_ID UUID,
  USER_EMAIL VARCHAR,
  USER_ROLE VARCHAR,
  USER_ACTIVE BOOLEAN,
  USER_CREATED_AT TIMESTAMP
)
LANGUAGE PLPGSQL
AS $$
BEGIN
  RETURN QUERY
  SELECT
    B.ID,
    B.NAME,
    B.PHONE,
    B.IS_ACTIVE,
    B.CREATED_AT,

    U.ID,
    U.EMAIL,
    U.ROLE,
    U.IS_ACTIVE,
    U.CREATED_AT
  FROM BUSINESSES B
  INNER JOIN USERS U
    ON U.BUSINESS_ID = B.ID
  ORDER BY B.CREATED_AT DESC, U.CREATED_AT DESC;
END;
$$;


-- ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_check;

-- ALTER TABLE users
--   ADD CONSTRAINT users_role_check
--   CHECK (role IN ('SUPER', 'ADMIN', 'PYME'));


-- ALTER TABLE users
--   ALTER COLUMN business_id DROP NOT NULL;


-- ALTER TABLE users DROP CONSTRAINT IF EXISTS users_super_business_null;

-- ALTER TABLE users
--   ADD CONSTRAINT users_super_business_null
--   CHECK (
--     (role = 'SUPER' AND business_id IS NULL)
--     OR (role <> 'SUPER' AND business_id IS NOT NULL)
--   );


-- INSERT INTO users (id, email, password_hash, role, business_id, is_active, created_at)
-- VALUES (
--   gen_random_uuid(),
--   'super@sinpeconectacr.com',
--   crypt('ChangeMe_Immediately123!', gen_salt('bf')),
--   'SUPER',
--   NULL,
--   TRUE,
--   NOW()
-- );


-- CREATE OR REPLACE FUNCTION SP_PLATFORM_CREATE_BUSINESS_WITH_OWNER(
--   P_SUPER_USER_ID  UUID,
--   P_BUSINESS_NAME  VARCHAR,
--   P_BUSINESS_PHONE VARCHAR,
--   P_OWNER_EMAIL    VARCHAR,
--   P_OWNER_PASSWORD VARCHAR,
--   P_IP             VARCHAR DEFAULT NULL,
--   P_USER_AGENT     TEXT DEFAULT NULL
-- )
-- RETURNS TABLE (
--   BUSINESS_ID UUID,
--   OWNER_USER_ID UUID,
--   OWNER_EMAIL VARCHAR,
--   OWNER_ROLE VARCHAR
-- )
-- LANGUAGE plpgsql
-- AS $$
-- DECLARE
--   V_ROLE VARCHAR;
--   V_BUSINESS_ID UUID := gen_random_uuid();
--   V_OWNER_USER_ID UUID := gen_random_uuid();
--   V_OWNER_HASH TEXT;
-- BEGIN
--   -- validate caller is SUPER
--   SELECT U.ROLE INTO V_ROLE
--   FROM USERS U
--   WHERE U.ID = P_SUPER_USER_ID
--     AND U.IS_ACTIVE = TRUE;

--   IF V_ROLE IS DISTINCT FROM 'SUPER' THEN
--     RAISE EXCEPTION 'FORBIDDEN_NOT_SUPER';
--   END IF;

--   -- unique owner email
--   IF EXISTS (SELECT 1 FROM USERS U WHERE U.EMAIL = P_OWNER_EMAIL) THEN
--     RAISE EXCEPTION 'USER_ALREADY_EXISTS';
--   END IF;

--   -- create business
--   INSERT INTO BUSINESSES (ID, NAME, PHONE, IS_ACTIVE, CREATED_AT)
--   VALUES (V_BUSINESS_ID, P_BUSINESS_NAME, P_BUSINESS_PHONE, TRUE, NOW());

--   -- create owner as ADMIN (or PYME if you prefer)
--   V_OWNER_HASH := crypt(P_OWNER_PASSWORD, gen_salt('bf'));

--   INSERT INTO USERS (ID, EMAIL, PASSWORD_HASH, ROLE, BUSINESS_ID, IS_ACTIVE, CREATED_AT)
--   VALUES (V_OWNER_USER_ID, P_OWNER_EMAIL, V_OWNER_HASH, 'ADMIN', V_BUSINESS_ID, TRUE, NOW());

--   -- audit
--   INSERT INTO AUTH_AUDIT_LOGS (USER_ID, BUSINESS_ID, ACTION, IP_ADDRESS, USER_AGENT)
--   VALUES (P_SUPER_USER_ID, V_BUSINESS_ID, 'SUPER_CREATE_BUSINESS', P_IP, P_USER_AGENT);

--   RETURN QUERY
--   SELECT V_BUSINESS_ID, V_OWNER_USER_ID, P_OWNER_EMAIL, 'ADMIN';
-- END;
-- $$;


-- CREATE OR REPLACE FUNCTION SP_BUSINESS_CREATE_USER(
--   P_ADMIN_USER_ID UUID,
--   P_EMAIL         VARCHAR,
--   P_PASSWORD      VARCHAR,
--   P_ROLE          VARCHAR DEFAULT 'PYME'
-- )
-- RETURNS TABLE (
--   USER_ID UUID,
--   EMAIL VARCHAR,
--   ROLE VARCHAR,
--   BUSINESS_ID UUID
-- )
-- LANGUAGE plpgsql
-- AS $$
-- DECLARE
--   V_ADMIN_ROLE VARCHAR;
--   V_BUSINESS_ID UUID;
--   V_USER_ID UUID := gen_random_uuid();
--   V_HASH TEXT;
-- BEGIN
--   SELECT U.ROLE, U.BUSINESS_ID INTO V_ADMIN_ROLE, V_BUSINESS_ID
--   FROM USERS U
--   WHERE U.ID = P_ADMIN_USER_ID AND U.IS_ACTIVE = TRUE;

--   IF V_ADMIN_ROLE NOT IN ('ADMIN') THEN
--     RAISE EXCEPTION 'FORBIDDEN_NOT_ADMIN';
--   END IF;

--   IF P_ROLE NOT IN ('PYME','ADMIN') THEN
--     RAISE EXCEPTION 'INVALID_ROLE';
--   END IF;

--   IF EXISTS (SELECT 1 FROM USERS U WHERE U.EMAIL = P_EMAIL) THEN
--     RAISE EXCEPTION 'USER_ALREADY_EXISTS';
--   END IF;

--   V_HASH := crypt(P_PASSWORD, gen_salt('bf'));

--   INSERT INTO USERS (ID, EMAIL, PASSWORD_HASH, ROLE, BUSINESS_ID)
--   VALUES (V_USER_ID, P_EMAIL, V_HASH, P_ROLE, V_BUSINESS_ID);

--   RETURN QUERY
--   SELECT V_USER_ID, P_EMAIL, P_ROLE, V_BUSINESS_ID;
-- END;
-- $$;




-- CREATE OR REPLACE FUNCTION SP_CRM_CONTACT_DELETE(
--   P_BUSINESS_ID UUID,
--   P_ID UUID
-- )
-- RETURNS TABLE (
--   DELETED BOOLEAN
-- )
-- LANGUAGE PLPGSQL
-- AS $$
-- BEGIN
--   IF EXISTS (
--     SELECT 1
--       FROM ORDERS O
--      WHERE O.BUSINESS_ID = P_BUSINESS_ID
--        AND O.CONTACT_ID = P_ID
--   ) THEN
--     RAISE EXCEPTION 'CONTACT_HAS_ORDERS';
--   END IF;

--   DELETE FROM CONTACTS
--    WHERE BUSINESS_ID = P_BUSINESS_ID
--      AND ID = P_ID;

--   RETURN QUERY
--   SELECT FOUND AS DELETED;
-- END;
-- $$;


-- INSERT INTO CONTACTS (ID, BUSINESS_ID, PHONE, NAME, EMAIL, NOTES)
-- VALUES
--   ('11111111-1111-1111-1111-111111111111', 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', '+50688881111', 'Juan Perez', 'juan@test.com', 'Cliente frecuente'),
--   ('22222222-2222-2222-2222-222222222222', 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', '+50688882222', 'Maria Lopez', 'maria@test.com', NULL),
--   ('33333333-3333-3333-3333-333333333333', 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', '+50688883333', 'Carlos Mora', NULL, 'Compra grande');

-- INSERT INTO ORDERS (ID, BUSINESS_ID, CONTACT_ID, ORDER_CODE, TOTAL_CRC, STATUS, DUE_DATE, NOTE)
-- VALUES
--   ('aaaa1111-0000-0000-0000-000000000001', 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
--    '11111111-1111-1111-1111-111111111111', 'ORD-20260122-0001', 12500, 'PENDING', '2026-01-25', 'Pendiente de pago'),

--   ('aaaa1111-0000-0000-0000-000000000002', 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
--    '22222222-2222-2222-2222-222222222222', 'ORD-20260122-0002', 22000, 'PAID', NULL, 'Pagado por SINPE'),

--   ('aaaa1111-0000-0000-0000-000000000003', 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
--    '33333333-3333-3333-3333-333333333333', 'ORD-20260122-0003', 18000, 'IN_REVIEW', NULL, 'Referencia dudosa');




-- CREATE OR REPLACE FUNCTION SP_CRM_DASHBOARD_SUMMARY(
--   P_BUSINESS_ID UUID
-- )
-- RETURNS TABLE (
--   CONTACTS_TOTAL BIGINT,
--   ORDERS_PENDING BIGINT,
--   ORDERS_PAID BIGINT,
--   ORDERS_IN_REVIEW BIGINT,
--   PENDING_TOTAL_CRC BIGINT
-- )
-- LANGUAGE SQL
-- AS $$
--   SELECT
--     (SELECT COUNT(1) FROM CONTACTS C WHERE C.BUSINESS_ID = P_BUSINESS_ID) AS CONTACTS_TOTAL,

--     (SELECT COUNT(1) FROM ORDERS O WHERE O.BUSINESS_ID = P_BUSINESS_ID AND O.STATUS = 'PENDING') AS ORDERS_PENDING,
--     (SELECT COUNT(1) FROM ORDERS O WHERE O.BUSINESS_ID = P_BUSINESS_ID AND O.STATUS = 'PAID') AS ORDERS_PAID,
--     (SELECT COUNT(1) FROM ORDERS O WHERE O.BUSINESS_ID = P_BUSINESS_ID AND O.STATUS = 'IN_REVIEW') AS ORDERS_IN_REVIEW,

--     (SELECT COALESCE(SUM(O.TOTAL_CRC), 0) FROM ORDERS O WHERE O.BUSINESS_ID = P_BUSINESS_ID AND O.STATUS = 'PENDING') AS PENDING_TOTAL_CRC;
-- $$;

-- CREATE OR REPLACE FUNCTION SP_CRM_ORDER_LIST(
--   P_BUSINESS_ID UUID,
--   P_STATUS VARCHAR DEFAULT NULL,
--   P_SEARCH TEXT DEFAULT NULL,
--   P_LIMIT INT DEFAULT 20,
--   P_OFFSET INT DEFAULT 0
-- )
-- RETURNS TABLE (
--   ID UUID,
--   BUSINESS_ID UUID,
--   CONTACT_ID UUID,
--   ORDER_CODE VARCHAR,
--   TOTAL_CRC INT,
--   STATUS VARCHAR,
--   DUE_DATE DATE,
--   NOTE TEXT,
--   CREATED_AT TIMESTAMPTZ,
--   UPDATED_AT TIMESTAMPTZ
-- )
-- LANGUAGE SQL
-- AS $$
--   SELECT
--     O.ID,
--     O.BUSINESS_ID,
--     O.CONTACT_ID,
--     O.ORDER_CODE,
--     O.TOTAL_CRC,
--     O.STATUS,
--     O.DUE_DATE,
--     O.NOTE,
--     O.CREATED_AT,
--     O.UPDATED_AT
--   FROM ORDERS O
--   WHERE O.BUSINESS_ID = P_BUSINESS_ID
--     AND (P_STATUS IS NULL OR P_STATUS = '' OR O.STATUS = P_STATUS)
--     AND (
--       P_SEARCH IS NULL OR P_SEARCH = '' OR
--       O.ORDER_CODE ILIKE ('%' || P_SEARCH || '%')
--     )
--   ORDER BY O.UPDATED_AT DESC
--   LIMIT P_LIMIT OFFSET P_OFFSET;
-- $$;

-- CREATE OR REPLACE FUNCTION SP_CRM_ORDER_CREATE(
--   P_BUSINESS_ID UUID,
--   P_CONTACT_ID UUID,
--   P_ORDER_CODE VARCHAR,
--   P_TOTAL_CRC INT,
--   P_STATUS VARCHAR DEFAULT 'PENDING',
--   P_DUE_DATE DATE DEFAULT NULL,
--   P_NOTE TEXT DEFAULT NULL
-- )
-- RETURNS TABLE (
--   ID UUID,
--   BUSINESS_ID UUID,
--   CONTACT_ID UUID,
--   ORDER_CODE VARCHAR,
--   TOTAL_CRC INT,
--   STATUS VARCHAR,
--   DUE_DATE DATE,
--   NOTE TEXT,
--   CREATED_AT TIMESTAMPTZ,
--   UPDATED_AT TIMESTAMPTZ
-- )
-- LANGUAGE PLPGSQL
-- AS $$
-- BEGIN
--   -- CONTACT MUST BELONG TO SAME BUSINESS
--   IF NOT EXISTS (
--     SELECT 1 FROM CONTACTS C
--      WHERE C.ID = P_CONTACT_ID
--        AND C.BUSINESS_ID = P_BUSINESS_ID
--   ) THEN
--     RAISE EXCEPTION 'CONTACT_NOT_FOUND';
--   END IF;

--   RETURN QUERY
--   INSERT INTO ORDERS (BUSINESS_ID, CONTACT_ID, ORDER_CODE, TOTAL_CRC, STATUS, DUE_DATE, NOTE)
--   VALUES (P_BUSINESS_ID, P_CONTACT_ID, P_ORDER_CODE, P_TOTAL_CRC, P_STATUS, P_DUE_DATE, P_NOTE)
--   RETURNING
--     ORDERS.ID,
--     ORDERS.BUSINESS_ID,
--     ORDERS.CONTACT_ID,
--     ORDERS.ORDER_CODE,
--     ORDERS.TOTAL_CRC,
--     ORDERS.STATUS,
--     ORDERS.DUE_DATE,
--     ORDERS.NOTE,
--     ORDERS.CREATED_AT,
--     ORDERS.UPDATED_AT;
-- END;
-- $$;

-- CREATE OR REPLACE FUNCTION SP_CRM_ORDER_UPDATE(
--   P_BUSINESS_ID UUID,
--   P_ID UUID,
--   P_TOTAL_CRC INT DEFAULT NULL,
--   P_DUE_DATE DATE DEFAULT NULL,
--   P_NOTE TEXT DEFAULT NULL
-- )
-- RETURNS TABLE (
--   ID UUID,
--   BUSINESS_ID UUID,
--   CONTACT_ID UUID,
--   ORDER_CODE VARCHAR,
--   TOTAL_CRC INT,
--   STATUS VARCHAR,
--   DUE_DATE DATE,
--   NOTE TEXT,
--   CREATED_AT TIMESTAMPTZ,
--   UPDATED_AT TIMESTAMPTZ
-- )
-- LANGUAGE PLPGSQL
-- AS $$
-- BEGIN
--   RETURN QUERY
--   UPDATE ORDERS O
--      SET TOTAL_CRC  = COALESCE(P_TOTAL_CRC, O.TOTAL_CRC),
--          DUE_DATE   = COALESCE(P_DUE_DATE, O.DUE_DATE),
--          NOTE       = COALESCE(P_NOTE, O.NOTE),
--          UPDATED_AT = NOW()
--    WHERE O.BUSINESS_ID = P_BUSINESS_ID
--      AND O.ID = P_ID
--   RETURNING
--     O.ID, O.BUSINESS_ID, O.CONTACT_ID, O.ORDER_CODE, O.TOTAL_CRC, O.STATUS,
--     O.DUE_DATE, O.NOTE, O.CREATED_AT, O.UPDATED_AT;
-- END;
-- $$;

-- CREATE OR REPLACE FUNCTION SP_CRM_ORDER_UPDATE_STATUS(
--   P_BUSINESS_ID UUID,
--   P_ID UUID,
--   P_STATUS VARCHAR
-- )
-- RETURNS TABLE (
--   ID UUID,
--   BUSINESS_ID UUID,
--   CONTACT_ID UUID,
--   ORDER_CODE VARCHAR,
--   TOTAL_CRC INT,
--   STATUS VARCHAR,
--   DUE_DATE DATE,
--   NOTE TEXT,
--   CREATED_AT TIMESTAMPTZ,
--   UPDATED_AT TIMESTAMPTZ
-- )
-- LANGUAGE PLPGSQL
-- AS $$
-- BEGIN
--   IF P_STATUS NOT IN ('PENDING', 'PAID', 'IN_REVIEW') THEN
--     RAISE EXCEPTION 'INVALID_STATUS';
--   END IF;

--   RETURN QUERY
--   UPDATE ORDERS O
--      SET STATUS     = P_STATUS,
--          UPDATED_AT = NOW()
--    WHERE O.BUSINESS_ID = P_BUSINESS_ID
--      AND O.ID = P_ID
--   RETURNING
--     O.ID, O.BUSINESS_ID, O.CONTACT_ID, O.ORDER_CODE, O.TOTAL_CRC, O.STATUS,
--     O.DUE_DATE, O.NOTE, O.CREATED_AT, O.UPDATED_AT;
-- END;
-- $$;

-- CREATE OR REPLACE FUNCTION SP_CRM_ORDER_DELETE(
--   P_BUSINESS_ID UUID,
--   P_ID UUID
-- )
-- RETURNS TABLE (
--   DELETED BOOLEAN
-- )
-- LANGUAGE PLPGSQL
-- AS $$
-- BEGIN
--   DELETE FROM ORDERS
--    WHERE BUSINESS_ID = P_BUSINESS_ID
--      AND ID = P_ID;

--   RETURN QUERY
--   SELECT FOUND AS DELETED;
-- END;
-- $$;


--   ID UUID,
--   BUSINESS_ID UUID,
--   PHONE VARCHAR,
--   NAME VARCHAR,
--   EMAIL VARCHAR,
--   NOTES TEXT,
--   CREATED_AT TIMESTAMPTZ,
--   UPDATED_AT TIMESTAMPTZ
-- )
-- LANGUAGE SQL
-- AS $$
--   SELECT
--     C.ID,
--     C.BUSINESS_ID,
--     C.PHONE,
--     C.NAME,
--     C.EMAIL,
--     C.NOTES,
--     C.CREATED_AT,
--     C.UPDATED_AT
--   FROM CONTACTS C
--   WHERE C.BUSINESS_ID = P_BUSINESS_ID
--     AND (
--       P_SEARCH IS NULL OR P_SEARCH = '' OR
--       C.PHONE ILIKE ('%' || P_SEARCH || '%') OR
--       C.NAME ILIKE ('%' || P_SEARCH || '%') OR
--       C.EMAIL ILIKE ('%' || P_SEARCH || '%')
--     )
--   ORDER BY C.UPDATED_AT DESC
--   LIMIT P_LIMIT OFFSET P_OFFSET;
-- $$;

-- CREATE OR REPLACE FUNCTION SP_CRM_CONTACT_CREATE(
--   P_BUSINESS_ID UUID,
--   P_PHONE VARCHAR,
--   P_NAME VARCHAR DEFAULT NULL,
--   P_EMAIL VARCHAR DEFAULT NULL,
--   P_NOTES TEXT DEFAULT NULL
-- )
-- RETURNS TABLE (
--   ID UUID,
--   BUSINESS_ID UUID,
--   PHONE VARCHAR,
--   NAME VARCHAR,
--   EMAIL VARCHAR,
--   NOTES TEXT,
--   CREATED_AT TIMESTAMPTZ,
--   UPDATED_AT TIMESTAMPTZ
-- )
-- LANGUAGE PLPGSQL
-- AS $$
-- BEGIN
--   RETURN QUERY
--   INSERT INTO CONTACTS (BUSINESS_ID, PHONE, NAME, EMAIL, NOTES)
--   VALUES (P_BUSINESS_ID, P_PHONE, P_NAME, P_EMAIL, P_NOTES)
--   RETURNING
--     CONTACTS.ID,
--     CONTACTS.BUSINESS_ID,
--     CONTACTS.PHONE,
--     CONTACTS.NAME,
--     CONTACTS.EMAIL,
--     CONTACTS.NOTES,
--     CONTACTS.CREATED_AT,
--     CONTACTS.UPDATED_AT;
-- END;
-- $$;

-- CREATE OR REPLACE FUNCTION SP_CRM_CONTACT_UPDATE(
--   P_BUSINESS_ID UUID,
--   P_ID UUID,
--   P_PHONE VARCHAR DEFAULT NULL,
--   P_NAME VARCHAR DEFAULT NULL,
--   P_EMAIL VARCHAR DEFAULT NULL,
--   P_NOTES TEXT DEFAULT NULL
-- )
-- RETURNS TABLE (
--   ID UUID,
--   BUSINESS_ID UUID,
--   PHONE VARCHAR,
--   NAME VARCHAR,
--   EMAIL VARCHAR,
--   NOTES TEXT,
--   CREATED_AT TIMESTAMPTZ,
--   UPDATED_AT TIMESTAMPTZ
-- )
-- LANGUAGE PLPGSQL
-- AS $$
-- BEGIN
--   RETURN QUERY
--   UPDATE CONTACTS C
--      SET PHONE      = COALESCE(P_PHONE, C.PHONE),
--          NAME       = COALESCE(P_NAME, C.NAME),
--          EMAIL      = COALESCE(P_EMAIL, C.EMAIL),
--          NOTES      = COALESCE(P_NOTES, C.NOTES),
--          UPDATED_AT = NOW()
--    WHERE C.BUSINESS_ID = P_BUSINESS_ID
--      AND C.ID = P_ID
--   RETURNING
--     C.ID, C.BUSINESS_ID, C.PHONE, C.NAME, C.EMAIL, C.NOTES, C.CREATED_AT, C.UPDATED_AT;
-- END;
-- $$;

-- CREATE OR REPLACE FUNCTION SP_CRM_CONTACT_DELETE(
--   P_BUSINESS_ID UUID,
--   P_ID UUID
-- )
-- RETURNS TABLE (
--   DELETED BOOLEAN
-- )
-- LANGUAGE PLPGSQL
-- AS $$
-- BEGIN
--   DELETE FROM CONTACTS
--    WHERE BUSINESS_ID = P_BUSINESS_ID
--      AND ID = P_ID;

--   RETURN QUERY
--   SELECT FOUND AS DELETED;
-- END;
-- $$;




-- -- CONTACTS
-- CREATE TABLE IF NOT EXISTS CONTACTS (
--   ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
--   BUSINESS_ID UUID NOT NULL,
--   PHONE VARCHAR(32) NOT NULL,
--   NAME VARCHAR(120),
--   EMAIL VARCHAR(160),
--   NOTES TEXT,
--   CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
--   UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
--   UNIQUE (BUSINESS_ID, PHONE)
-- );

-- -- ORDERS / FACTURAS
-- CREATE TABLE IF NOT EXISTS ORDERS (
--   ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
--   BUSINESS_ID UUID NOT NULL,
--   CONTACT_ID UUID NOT NULL
--     REFERENCES CONTACTS(ID) ON DELETE RESTRICT,
--   ORDER_CODE VARCHAR(40) NOT NULL, -- ORD-YYYYMMDD-0001
--   TOTAL_CRC INTEGER NOT NULL CHECK (TOTAL_CRC >= 0),
--   STATUS VARCHAR(20) NOT NULL
--     CHECK (STATUS IN ('PENDING', 'PAID', 'IN_REVIEW')),
--   DUE_DATE DATE,
--   NOTE TEXT,
--   CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
--   UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
--   UNIQUE (BUSINESS_ID, ORDER_CODE)
-- );

-- -- OPTIONAL: ORDER ITEMS
-- CREATE TABLE IF NOT EXISTS ORDER_ITEMS (
--   ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
--   ORDER_ID UUID NOT NULL
--     REFERENCES ORDERS(ID) ON DELETE CASCADE,
--   NAME VARCHAR(140) NOT NULL,
--   QTY INTEGER NOT NULL CHECK (QTY > 0),
--   UNIT_PRICE_CRC INTEGER NOT NULL CHECK (UNIT_PRICE_CRC >= 0)
-- );

-- -- INDEXES
-- CREATE INDEX IF NOT EXISTS IDX_CONTACTS_BUSINESS
--   ON CONTACTS (BUSINESS_ID);

-- CREATE INDEX IF NOT EXISTS IDX_ORDERS_BUSINESS_STATUS
--   ON ORDERS (BUSINESS_ID, STATUS);

-- CREATE INDEX IF NOT EXISTS IDX_ORDERS_CONTACT
--   ON ORDERS (CONTACT_ID);


-- CREATE OR REPLACE FUNCTION SP_AUTH_REGISTER(
--   P_BUSINESS_NAME   VARCHAR,
--   P_BUSINESS_PHONE  VARCHAR,
--   P_EMAIL           VARCHAR,
--   P_PASSWORD        VARCHAR,
--   P_IP              VARCHAR DEFAULT NULL,
--   P_USER_AGENT      TEXT DEFAULT NULL
-- )
-- RETURNS TABLE (
--   USER_ID UUID,
--   EMAIL VARCHAR,
--   ROLE VARCHAR,
--   BUSINESS_ID UUID
-- )
-- LANGUAGE plpgsql
-- AS $$
-- DECLARE
--   V_BUSINESS_ID UUID := gen_random_uuid();
--   V_USER_ID UUID := gen_random_uuid();
--   V_PASSWORD_HASH TEXT;
--   V_ROLE VARCHAR := 'PYME';
-- BEGIN
--   -- Unique email check (avoid ambiguity)
--   IF EXISTS (SELECT 1 FROM USERS U WHERE U.EMAIL = P_EMAIL) THEN
--     RAISE EXCEPTION 'USER_ALREADY_EXISTS';
--   END IF;

--   -- Hash password
--   V_PASSWORD_HASH := crypt(P_PASSWORD, gen_salt('bf'));

--   -- Insert business
--   INSERT INTO BUSINESSES (ID, NAME, PHONE)
--   VALUES (V_BUSINESS_ID, P_BUSINESS_NAME, P_BUSINESS_PHONE);

--   -- Insert user
--   INSERT INTO USERS (ID, EMAIL, PASSWORD_HASH, ROLE, BUSINESS_ID)
--   VALUES (V_USER_ID, P_EMAIL, V_PASSWORD_HASH, V_ROLE, V_BUSINESS_ID);

--   -- Audit
--   INSERT INTO AUTH_AUDIT_LOGS (USER_ID, BUSINESS_ID, ACTION, IP_ADDRESS, USER_AGENT)
--   VALUES (V_USER_ID, V_BUSINESS_ID, 'REGISTER_SUCCESS', P_IP, P_USER_AGENT);

--   -- Return EXACTLY (USER_ID, EMAIL, ROLE, BUSINESS_ID)
--   RETURN QUERY
--   SELECT
--     V_USER_ID::UUID,
--     P_EMAIL::VARCHAR,
--     V_ROLE::VARCHAR,
--     V_BUSINESS_ID::UUID;

-- END;
-- $$;

-- CREATE OR REPLACE FUNCTION SP_AUTH_LOGIN(
--   P_EMAIL       VARCHAR,
--   P_PASSWORD    VARCHAR,
--   P_IP          VARCHAR DEFAULT NULL,
--   P_USER_AGENT  TEXT DEFAULT NULL
-- )
-- RETURNS TABLE (
--   USER_ID UUID,
--   EMAIL VARCHAR,
--   ROLE VARCHAR,
--   BUSINESS_ID UUID
-- )
-- LANGUAGE plpgsql
-- AS $$
-- DECLARE
--   V_USER_ID UUID;
--   V_EMAIL VARCHAR;
--   V_PASSWORD_HASH TEXT;
--   V_ROLE VARCHAR;
--   V_BUSINESS_ID UUID;
--   V_IS_ACTIVE BOOLEAN;
-- BEGIN
--   -- Get user (explicit columns to avoid ambiguity)
--   SELECT
--     U.ID,
--     U.EMAIL,
--     U.PASSWORD_HASH,
--     U.ROLE,
--     U.BUSINESS_ID,
--     U.IS_ACTIVE
--   INTO
--     V_USER_ID,
--     V_EMAIL,
--     V_PASSWORD_HASH,
--     V_ROLE,
--     V_BUSINESS_ID,
--     V_IS_ACTIVE
--   FROM USERS U
--   WHERE U.EMAIL = P_EMAIL
--   LIMIT 1;

--   -- If user not found or inactive
--   IF V_USER_ID IS NULL OR V_IS_ACTIVE IS DISTINCT FROM TRUE THEN
--     INSERT INTO AUTH_AUDIT_LOGS (ACTION, IP_ADDRESS, USER_AGENT)
--     VALUES ('LOGIN_FAILED', P_IP, P_USER_AGENT);
--     RAISE EXCEPTION 'INVALID_CREDENTIALS';
--   END IF;

--   -- Validate password using pgcrypto crypt()
--   IF NOT (V_PASSWORD_HASH = crypt(P_PASSWORD, V_PASSWORD_HASH)) THEN
--     INSERT INTO AUTH_AUDIT_LOGS (
--       USER_ID, BUSINESS_ID, ACTION, IP_ADDRESS, USER_AGENT
--     ) VALUES (
--       V_USER_ID, V_BUSINESS_ID, 'LOGIN_FAILED', P_IP, P_USER_AGENT
--     );
--     RAISE EXCEPTION 'INVALID_CREDENTIALS';
--   END IF;

--   -- Audit success
--   INSERT INTO AUTH_AUDIT_LOGS (
--     USER_ID, BUSINESS_ID, ACTION, IP_ADDRESS, USER_AGENT
--   ) VALUES (
--     V_USER_ID, V_BUSINESS_ID, 'LOGIN_SUCCESS', P_IP, P_USER_AGENT
--   );

--   RETURN QUERY
--   SELECT V_USER_ID, V_EMAIL, V_ROLE, V_BUSINESS_ID;
-- END;
-- $$;

-- CREATE TABLE businesses (
--   id UUID PRIMARY KEY,
--   name VARCHAR(150) NOT NULL,
--   phone VARCHAR(30) NOT NULL,
--   is_active BOOLEAN NOT NULL DEFAULT TRUE,
--   created_at TIMESTAMP NOT NULL DEFAULT NOW()
-- );

-- CREATE TABLE users (
--   id UUID PRIMARY KEY,
--   email VARCHAR(150) NOT NULL UNIQUE,
--   password_hash TEXT NOT NULL,
--   role VARCHAR(20) NOT NULL CHECK (role IN ('ADMIN', 'PYME')),
--   business_id UUID NOT NULL,
--   is_active BOOLEAN NOT NULL DEFAULT TRUE,
--   created_at TIMESTAMP NOT NULL DEFAULT NOW(),

--   CONSTRAINT fk_users_business
--     FOREIGN KEY (business_id)
--     REFERENCES businesses(id)
--     ON DELETE RESTRICT
-- );

-- CREATE INDEX idx_users_business_id ON users(business_id);
-- CREATE INDEX idx_users_email ON users(email);

-- CREATE TABLE auth_audit_logs (
--   id BIGSERIAL PRIMARY KEY,
--   user_id UUID,
--   business_id UUID,
--   action VARCHAR(50) NOT NULL,
--   ip_address VARCHAR(45),
--   user_agent TEXT,
--   created_at TIMESTAMP NOT NULL DEFAULT NOW()
-- );

-- CREATE INDEX idx_audit_business_id ON auth_audit_logs(business_id);
-- CREATE INDEX idx_audit_user_id ON auth_audit_logs(user_id);

-- INSERT INTO businesses (
--   id,
--   name,
--   phone,
--   is_active,
--   created_at
-- ) VALUES (
--   '11111111-1111-1111-1111-111111111111',
--   'Panadería San José',
--   '+50688887777',
--   TRUE,
--   NOW()
-- );

-- INSERT INTO users (
--   id,
--   email,
--   password_hash,
--   role,
--   business_id,
--   is_active,
--   created_at
-- ) VALUES (
--   '22222222-2222-2222-2222-222222222222',
--   'admin@panaderia.com',
--   '$2b$10$eImiTXuWVxfM37uY4JANjQexamplehashxxxxxxxxxxxxxxxxxxxxx',
--   'PYME',
--   '11111111-1111-1111-1111-111111111111',
--   TRUE,
--   NOW()
-- );

-- INSERT INTO auth_audit_logs (
--   user_id,
--   business_id,
--   action,
--   ip_address,
--   user_agent,
--   created_at
-- ) VALUES (
--   '22222222-2222-2222-2222-222222222222',
--   '11111111-1111-1111-1111-111111111111',
--   'LOGIN_SUCCESS',
--   '127.0.0.1',
--   'Postman',
--   NOW()
-- );
